### PR TITLE
ensure valid coordinates by intersection with parent…

### PR DESCRIPTION
**Pull request by bertsky**
- Border: intersect with page frame
- text regions: intersect with (new) Border
- text lines: intersect with (new) text region
  (and back-transform at all)

This fixes the negative coordinates, and also the line-region inconsistency (line bboxes way beyond tight region outlines).

I'll fix removing the existing derived images with `cropped` in a PR to core, so this will be transparent and automatic here.

### CODE REVIEW

**Comment by bertsky** [comment]
Oh, and could you please try introducing _some_ versioning (so users get to see what version produced their PAGE/METS annotations)?

**Comment by bertsky** [comment]
> I'll fix removing the existing derived images with `cropped` in a PR to core, so this will be transparent and automatic here.

https://github.com/OCR-D/core/pull/639

**Comment by jbarth-ubhd** [comment]
I've tried it again (with `make NO_UPDATE=1 all` after `git remote add bertsky https://github.com/bertsky/sbb_textline_detection`) , but get no text simple-layout pages.

Just to be sure I've grepped a string from https://github.com/qurator-spk/sbb_textline_detection/compare/master...bertsky:fix-coords : 
```
(venv) [hd_xxxxx@login5 sbb_textline_detector]$ pwd
/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/local/sub-venv/headless-tf1/lib/python3.7/site-packages/qurator/sbb_textline_detector
(venv) [hd_xxxxx@login5 sbb_textline_detector]$ grep -r 'new border would be empty, skipping' .
./ocrd_cli.py:                log.warning("new border would be empty, skipping")
Binary file ./__pycache__/ocrd_cli.cpython-37.pyc matches
```

So the my venv seems up to date(?)

**Comment by jbarth-ubhd** [comment]
example: https://digi.ub.uni-heidelberg.de/diglitData/v/ocrd/dobbert1861-empty.tgz

**Comment by bertsky** [comment]
> with `make NO_UPDATE=1 all`

Did you `git -C core pull origin` before that? (You need an up-to-date core also in the sub-venv.)

> but get no text simple-layout pages.

You get what?

**Comment by jbarth-ubhd** [comment]
No Text from ...

Von meinem iPhone gesendet

Am 05.11.2020 um 15:04 schrieb Robert Sachunsky <notifications@github.com>:

﻿

with make NO_UPDATE=1 all

Did you git -C core pull origin before that? (You need an up-to-date core also in the sub-venv.)

but get no text simple-layout pages.

You get what?

**Comment by jbarth-ubhd** [comment]
hmmm...
```
[hd_xxx@login5 ocrd_all]$ ~/local/bin/git -C core pull origin
warning: Es wird davon abgeraten zu Pullen, ohne anzugeben, wie mit abweichenden
Branches umgegangen werden soll. Sie können diese Nachricht unterdrücken,
...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 45 (delta 24), reused 34 (delta 19), pack-reused 0
Entpacke Objekte: 100% (45/45), 129.57 KiB | 93.00 KiB/s, Fertig.
Von https://github.com/OCR-D/core
   c8136bf5..ffe4e545  master     -> origin/master
 * [neues Tag]         v2.20.0    -> v2.20.0
Im Moment auf keinem Branch.
Bitte geben Sie den Branch an, welchen Sie zusammenführen möchten.
Siehe git-pull(1) für weitere Details.

    git pull <Remote-Repository> <Branch>

[hd_xxx@login5 ocrd_all]$ make NO_UPDATE=1 all
make: Nothing to be done for `all'.
```

ok I'll wait till your changes are pulled into ocrd_all.

**Comment by jbarth-ubhd** [comment]
oops. `~/local/bin/git -C core pull origin master` seems to help.

**Comment by bertsky** [comment]
> This fixes the negative coordinates, and also the line-region inconsistency (line bboxes way beyond tight region outlines).

I don't understand why this essential fix has not been merged yet.

**Review by kba — APPROVED** [review]

**Comment by cneud** [comment]
Thank you for the contribution! For internal reasons, we have not had the time to properly review this yet. I will put it on the agenda for our next internal meeting.

**Review by vahidrezanezhad — APPROVED** [review]

**Pull request merged**
